spring:
  datasource:
    url: jdbc:mysql://localhost:3306/aaa
    username: root
    password: lwy0328
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    properties:
      hibernate:
        hbm2ddl:
          auto: update